# Define the goal
navigation_msgs/PoseStamped goal
float32 max_linear_velocity
float32 max_linear_acceleration
float32 max_angular_velocity
---
# Define the result
bool success
---
# Define a feedback 
